#!/usr/bin/env bash

set -euo pipefail

echo "~~~ Setup Fly.io"

# TODO: Negotiate operating system
FLYIO_OS="linux" # or darwin, freebsd, openbsd, solaris, windows

export FLYCTL_INSTALL="$HOME/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

if ! command -v flyctl &> /dev/null
then
  curl -L https://fly.io/install.sh | sh
fi

flyctl version

echo "~~~ Verify Fly.io identify"

flyctl auth whoami
