#!/usr/bin/env bash

set -euo pipefail

echo "~~~ Setup Fly.io"

if ! command -v flyctl &> /dev/null
then
  # TODO: Negotiate operating system
  FLYIO_OS="linux" # or darwin, freebsd, openbsd, solaris, windows

  curl -L https://fly.io/install.sh | sh
fi

flyctl version

echo "~~~ Verify Fly.io identify"

flyctl auth whoami
